### ISSUE TITLE
Необходимо выделять текущий раздел в левом меню документации

### ISSUE THREAD

**Issue by Sergey-Shabanov** [LaravelRUS/laravel.su#23]
Возможно, заметное выделение текущего пункта меню, и удержание скроллинга списка пунктов на выбранном, улучшит пользовательский опыт, и позволит лучше ориентироваться в документации. 

По личному опыту, при переходе на пункт меню который ниже первой страницы экрана, страница обновляется и выбранный пункт оказывается за нижней границей. Более того, он ни как не выделяется, и чтобы перейти к следующему пункту, приходится скролить страницу, выискивая глазами текущий пункт.

![image](https://user-images.githubusercontent.com/57292074/118501843-b5817800-b75b-11eb-8e27-e7844f51f2b9.png)

Текущий пункт меню необходимо выделить через класс CSS, а если реализовать автопрокрутку меню к текущему пункту после обновления страницы, то это будет "бомба".

Я не изучал, как работает ваш движок, но возможно могу помочь реализовать указанные поведения, так как в том числе занимаюсь версткой сайтов.

**Comment by Sergey-Shabanov** [comment]
Предлагаю частичное решение, через подсветку текущего пункта меню, без скроллинга. 

Пуллреквест https://github.com/LaravelRUS/laravel.su/pull/28

**Comment by SerafimArts** [comment]
@Sergey-Shabanov закрывать ишью?

**Comment by Sergey-Shabanov** [comment]
> @Sergey-Shabanov закрывать ишью?

да, mvp готово
